# Исправленный docker-compose.yml
version: '3.8'

services:
  brass_server:
    image: brass_server:latest
    container_name: brass_server
    restart: always
    env_file:
      - .env
    environment:
      # Надежно передаем порт в приложение
      JAVA_OPTS: "-Dserver.port=8081"
    ports:
      # Теперь пробрасываем 8081 на 8081
      - "8081:8081"