version: '3.8'

services:
  regent_server:
    image: brass_server:latest
    container_name: brass_server
    restart: always
    env_file:
      - .env  # Добавляем ссылку на .env файл, который будет использоваться для переменных окружения
    ports:
      - "8081:8080"