name: Java CI with Maven, Docker Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_IMAGE: "brass_server"
  DEPLOY_DIR: "/root/brass_server/"
  CONTAINER_NAME: "brass_server"
  HOST_PORT: "8081"
  CONTAINER_PORT: "8081"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка исходного кода
      - uses: actions/checkout@v4

      # Шаг 2: Список файлов в рабочей директории
      - name: List files in the working directory
        run: ls -la

      # Шаг 3: Настройка JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # Шаг 4: Сборка с Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Шаг 5: Настройка Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Шаг 6: Сборка Docker-образа
      - name: Build Docker image
        run: |
          docker build -t $DOCKER_IMAGE .
          docker images

      # Шаг 7: Сохранение Docker-образа в файл
      - name: Save Docker image
        run: |
          docker save $DOCKER_IMAGE -o $DOCKER_IMAGE.tar
          ls -lh

      # Шаг 8: Установка sshpass
      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      # Шаг 9: Копирование Docker-образа и docker-compose.yml на сервер
      - name: Copy Docker image and docker-compose.yml to remote server
        run: |
          # Копирование Docker-образа на сервер
          sshpass -p "${{ secrets.SUDO_PASSWORD }}" scp -o StrictHostKeyChecking=no \
            $DOCKER_IMAGE.tar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:$DEPLOY_DIR
          
          # Копирование docker-compose.yml на сервер
          sshpass -p "${{ secrets.SUDO_PASSWORD }}" scp -o StrictHostKeyChecking=no \
            docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:$DEPLOY_DIR

          # Шаг для создания нового docker-compose.yml с подставленными переменными окружения
          sshpass -p "${{ secrets.SUDO_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
            # Замена переменных в docker-compose.yml
            export SPRING_DATASOURCE_URL="${{ secrets.SPRING_DATASOURCE_URL }}"
            export SPRING_DATASOURCE_USERNAME="${{ secrets.SPRING_DATASOURCE_USERNAME }}"
            export SPRING_DATASOURCE_PASSWORD="${{ secrets.SPRING_DATASOURCE_PASSWORD }}"
          EOF

  deploy-to-server:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Шаг 1: Установка sshpass на сервере
      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      # Шаг 2: Создание директории для деплоя на сервере (если её нет)
      - name: Create deploy directory on remote server
        run: |
          sshpass -p "${{ secrets.SUDO_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
            # Создание директории, если она не существует
            mkdir -p /root/deploy_regent_server/
            # Установка прав доступа для директории
            chmod -R 777 /root/deploy_regent_server/
          EOF

      # Шаг 3: Развёртывание Docker-образа на сервере
      - name: Deploy Docker image on remote server
        run: |
          sshpass -p "${{ secrets.SUDO_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
            cd /root/deploy_regent_server/
          
            # Остановка и удаление старого контейнера
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
            # Удаление старого образа
            docker rmi $DOCKER_IMAGE || true
            # Развёртывание нового контейнера
            docker load -i /root/deploy_regent_server/$DOCKER_IMAGE.tar
            docker-compose up -d --force-recreate
          EOF